### ISSUE TITLE
false positive xfs-000.animemark.net

### ISSUE THREAD

**Issue by Uranite** [j-moriarti/pDNSf-Hosts-collection#11]
https://bato.to/series/88296
the thumbnail

**Comment by j-moriarti** [comment]
Thanks for your reporting! :+1: I checked and found that it was blocked by this source: [badmojr_1hosts_xtra](https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/domains.txt). It will be fixed in next update! Also I have reported it to that source maintainer.
