### ISSUE TITLE
Optimize/compress the output files.

### ISSUE THREAD

**Issue by badmojr** [j-moriarti/pDNSf-Hosts-collection#4]
Hello!
Just wanted to bring this to your attention as (DNS) filterlist maintainers are starting to implement this.
eg.
https://github.com/hectorm/hblock/commit/21b4c3d7874319a2fb90de35444dfa07169696ec
https://github.com/mkb2091/blockconvert/commit/498dc474a916cc755c0197730a3410af3d37942e#diff-598405dde0944f981bc7fa79065f7006865f1169c1c2766ae6ab620e1136df9aR351

I've tested the current list (2021-03-14) and the domains count went down significantly when redundant subdomains (1,465,313) got removed.
Cheers!

**Comment by j-moriarti** [comment]
Hi!
Thanks for informing me about this! Actually, I had already tried to do something similar in the past, but my code was not optimized and took around 30-60 minutes to remove subdomains of a 60MB sized block-list!
But with the info you mentioned, I re-implemented it here (https://github.com/j-moriarti/pDNSf-Hosts-collection/commit/73d387489c225503ec46639dfde25976a8bc3b1e) and now it takes only a few seconds!!! thanks again for your help! :+1: 

It will be great to inform me about any issues or this kind of enhancements! I will be more than happy to hear and fix it :wink: :smile:

**Comment by badmojr** [comment]
Quite a lot of redundunt subdomains have been removed.
There is quite alot, though, that the scprit missed.
eg. subdomains for _`taboola.com`_

**Comment by j-moriarti** [comment]
> 
> 
> eg. subdomains for _`taboola.com`_

Oh, Nice catch!
seems there was an issue with prioritizing the (-) character over dot(.) while sorting list.
it should be fixed by https://github.com/j-moriarti/pDNSf-Hosts-collection/commit/0d0595a0eddc94c517aa99b74492eba91b2b2925 (Hopefully)
Thanks again for helping and reporting this! :+1:

**Comment by badmojr** [comment]
No more redundant subdomains. 👍
Keep up the good work!
